function conductorDataResults = importfile46(filename, dataLines)
%IMPORTFILE46 Import data from a text file
%  CONDUCTORDATARESULTS = IMPORTFILE46(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  CONDUCTORDATARESULTS = IMPORTFILE46(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  conductorDataResults = importfile46("C:\Users\ctc\Documents\GitHub\Chapter3\conductorDataResults.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Jul-2019 13:10:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 29);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["CodeWord", "Size", "Stranding", "IndDiamAl", "IndDiamSt", "DiamStlCore", "DiamCompleteCable", "Weightper1000ftAl", "Weightper1000ftStl", "Weightper1000ftTotal", "Al", "Stl", "RatedStrength", "ResistanceDCLowdegc", "ResistanceACHighdegc", "LowTemp", "HighTemp", "MetersperResistanceInterval", "AllowableAmpacity", "Type", "ResistanceACLowdegc", "ResistanceACLowdegcMeter", "ResistanceACHighdegcMeter", "simulated", "convergeCurrent", "lowestRise", "convergenceOrder", "Cmax", "Cmin"];
opts.VariableTypes = ["string", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 3, 20], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
conductorDataResults = readtable(filename, opts);

end