function PMUData = importfile2(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  PMUDATA = IMPORTFILE2(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  PMUDATA = IMPORTFILE2(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  PMUData = importfile2("C:\Users\ctc\Documents\GitHub\Chapter4\BC\PMUData.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Apr-2019 08:51:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "VsMag", "VsPhase", "VrMag", "VrPhase", "IsMag", "IsPhase", "IrMag", "IrPhase", "FrMag", "FsMag", "VsMagStd", "VsPhaseStd", "VrMagStd", "VrPhaseStd", "IsMagStd", "IsPhaseStd", "IrMagStd", "IrPhaseStd", "FrMagStd", "FsMagStd"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "dd-MMM-yyyy HH:mm:ss");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PMUData = readtable(filename, opts);

end