function ConductorInfo = importfile1(filename, dataLines)
%IMPORTFILE6 Import data from a text file
%  CONDUCTORINFO = IMPORTFILE6(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CONDUCTORINFO = IMPORTFILE6(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ConductorInfo = importfile6("C:\Users\ctc\Documents\GitHub\Chapter3\ConductorInfo.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jun-2020 13:25:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["CodeWord", "Size", "Stranding", "IndDiamAl", "IndDiamSt", "DiamStlCore", "DiamCompleteCable", "Weightper1000ftAl", "Weightper1000ftStl", "Weightper1000ftTotal", "Al", "Stl", "RatedStrength", "ResistanceDCLowdegc", "ResistanceACHighdegc", "LowTemp", "HighTemp", "MetersperResistanceInterval", "AllowableAmpacity", "Type"];
opts.VariableTypes = ["string", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "CodeWord", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CodeWord", "Stranding", "Type"], "EmptyFieldRule", "auto");

% Import the data
ConductorInfo = readtable(filename, opts);

end